author: Introduction to Cryptography Course Team, built with <a href="https://teachbooks.io">TeachBooks</a>, <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="license noopener noreferrer"">CC BY 4.0<img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/cc.svg" alt=""><img style="height:22px!important;margin-left:3px;vertical-align:text-bottom;" src="https://mirrors.creativecommons.org/presskit/icons/by.svg" alt=""></a>
copyright: "2026"
title: Introduction to Cryptography

execute:
  execute_notebooks: "off"
  exclude_patterns: []
  timeout: 30
  allow_errors: false

parse:
  myst_enable_extensions:
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - substitution
    - tasklist
  myst_url_schemes: [mailto, http, https]
  myst_links_external_new_tab: true
  myst_dmath_double_inline: true

only_build_toc_files: true

html:
  use_multitoc_numbering: false

repository:
  url: https://github.com/HusseinYounis/cryptography-book
  path_to_book: book
  branch: main

bibtex_bibfiles:
  - references.bib

latex:
  latex_documents:
    targetname: book.tex

teachbooks:
  attribution_location: top
  attribution_color: attributiongrey

sphinx:
  extra_extensions:
    - teachbooks_favourites  # replaces all individual TeachBooks extensions
    - sphinxcontrib.mermaid
  config:
    mermaid_output_format: "png"
    mermaid_params: ["--scale", "3"]
    html_theme: sphinx_book_theme
    html_js_files:
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
    thebe_config:
      use_thebe_lite: true
      exclude_patterns: ["**/_*.yml", "**/*.md", "**/*.ipynb"]
    html_favicon: "figures/favicon.ico"
    html_baseurl: "https://husseinyounis.github.io/cryptography-book/"
    html_theme_options:
      navigation_with_keys: false
      show_nav_level: 2
      use_sidenotes: true
      launch_buttons:
        thebe: true
      use_edit_page_button: true
      use_repository_button: true
      use_issues_button: true
      announcement: ""
      repository_url: "https://github.com/HusseinYounis/cryptography-book"
      path_to_docs: "book"
      repository_branch: "main"
      logo:
        image_dark: figures/logo_dark.png
        image_light: figures/logo_light.png
        text: Introduction to Cryptography
    html_context:
      default_mode: light
    html_show_copyright: false
    html_last_updated_fmt: ''
    html_static_path: ["figures"]
    mathjax3_config:
      chtml:
        mtextInheritFont: true
    keep_warnings: false
    external_toc_exclude_missing: true
    inverter_all: true
    iframe_blend: true
    iframe_aspectratio: auto 2 / 1
    hide_solutions: false
    named_colors_custom_colors: {'attributiongrey':[150,150,150]}
    git_untracked_check_dependencies: false
    git_untracked_show_sourcelink: true
    git_last_updated_timezone: 'UTC'
    zoomies_selector: ".bd-article img, .bd-article .mermaid svg"
    zoomies_best_fit: 70
    zoomies_toolbar: ["zoomIn", "zoomOut", "oneToOne", "reset"]
    zoomies_invert_colors: false
    zoomies_bg_apply_to_img: true
    mathjax3_config:
      loader:
        load: ['[tex]/color']
      tex:
        packages:
          '[+]': ['color']
        macros:
          "orange": ['{{\\color{{orange}}{#1}}}', 1]
          "red": ['{{\\color{{red}}{#1}}}', 1]
          "blue": ['{{\\color{{blue}}{#1}}}', 1]
          "green": ['{{\\color{{green}}{#1}}}', 1]
    bibtex_bibfiles:
      - references.bib
    bibtex_reference_style: author_year
    thebe_config:
      repository_url: https://github.com/HusseinYounis/cryptography-book
      repository_branch: main
      path_to_book: book
      use_thebe_lite: true
      use_jupyter_lite: true
    tippy_props:
      maxWidth: 600
      placement: "top"
      interactive: true
      theme: "material"
    tippy_enable_mathjax: true
    tippy_rtd_urls: []
    inverter_all: true

